site_name: ForrestHub
site_url: https://forresthub.helceletka.cz
site_author: Jakub Andrýsek
site_description: >-
  🎮 ForrestHub je jednoduchá webová platforma umožňující navrhovat hry pro více hráčů které mezí sebou komunikují.

# Repository
repo_name: Helceletka/ForrestHub
repo_url: https://github.com/Helceletka/ForrestHub



theme:
  name: material
  language: en
  logo: graphics/ForrestHub-icon.svg
  favicon: graphics/ForrestHub-icon.svg
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JakubAndrysek
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jakub-andrysek/
  analytics:
    provider: google
    property: G-FGPKM4ZKVP

use_directory_urls: True

plugins:
  - search
  - open-in-new-tab
  - glightbox

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - def_list
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - markdown.extensions.md_in_html
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.blocks.admonition:
      types:
        - new
        - settings
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
  - pymdownx.blocks.details:
  - pymdownx.blocks.html:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Instalace: install/index.md
  - Generování her: game/index.md
  - Propojení her: connection/index.md