build-window:
	pyinstaller --onefile --add-data 'templates;templates' --add-data 'static;static' --icon=static\forester.ico --name="Forester" .\main.py

build-linux:
	pyinstaller --onefile --add-data 'templates:templates' --add-data 'static:static' main.py