build-window:
	pyinstaller --onefile --add-data 'templates;templates' --add-data 'static;static' .\main.py

build-linux:
	pyinstaller --onefile --add-data 'templates:templates' --add-data 'static:static' main.py