name: Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    permissions: write-all
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install setuptools
      - name: Install setuptools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools

      # Načtení verze z ForrestHub-app/setup.py a zjištění data (PowerShell)
      - name: Get version and date
        run: |
          cd ForrestHub-app
          $version = python setup.py --version
          echo "VERSION=$version" >> $env:GITHUB_ENV
          $dateStr = Get-Date -Format "yyyyMMdd"
          echo "DATESTR=$dateStr" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd ForrestHub-app
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          cd ForrestHub-app
          pyinstaller pyinstaller.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ForrestHub-Windows-${{ env.VERSION }}-${{ env.DATESTR }}
          path: ForrestHub-app/dist/ForrestHub.exe

  build-macos:
    permissions: write-all
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Načtení verze z ForrestHub-app/setup.py a zjištění data (bash)
      - name: Get version and date
        run: |
          cd ForrestHub-app
          VERSION=$(python setup.py --version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          DATESTR=$(date +'%Y%m%d')
          echo "DATESTR=$DATESTR" >> $GITHUB_ENV
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd ForrestHub-app
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          cd ForrestHub-app
          pyinstaller pyinstaller.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ForrestHub-macOS-${{ env.VERSION }}-${{ env.DATESTR }}
          path: ForrestHub-app/dist/ForrestHub
